-- CREATE TABLE
--     contactTBL (
--         customer_address varchar(50),
--         customer_phone varchar(20),
--         customer_email varchar(50),
--         customer_comment varchar(1000)
--     );
-- CREATE TABLE
--     registerTBL (
--         customer_fullname varchar(50),
--         customer_email varchar(50),
--         customer_phone varchar(20),
--         customer_exam_type varchar(20)
--     )
-- INSERT INTO contactTBL 
-- (customer_address, customer_phone, customer_email, customer_comment) 
-- VALUES ( 'No. 9 DLA ASABA DELTA STATE', '08059060890', 'dogunfx@gmail.com', 'nothing much' );
-- INSERT INTO contactTBL 
-- (customer_address, customer_phone, customer_email, customer_comment) 
-- VALUES ( '22 Warri Street ', '08057197137', 'miro@gmail.com', 'I would like to take an exam');
-- INSERT INTO
--     contactTBL (customer_address, customer_email, customer_phone)
-- VALUES
--     ("my address", '');
-- CREATE TABLE users (
--     name varchar(50),
--     email varchar(50),
--     password varchar(255),
--     id int 
-- );
-- INSERT INTO
--     users (name, email, password, id)
-- VALUES
--     (
--         "dogunfx",
--         "dogunfx@gmail.com",
--         '$2y$10$QBgiZUaZ3ZXEeaC6RSxbeu9wpqQUmWN4Sxo.GbUbC3cw0W3KWF1T6',
--         4
--     );
-- DELETE FROM users
-- WHERE
--     id = 3;